apiVersion: v2
name: helm-chart-bridge
description: Generic multi-tenant Helm chart for the Bridge tenant stack
type: application
version: 0.3.4
appVersion: "1.0"
annotations:
  org.opencontainers.image.source: https://github.com/sandeepkosework/helm-chart-bridge
