{{- if .Values.tenantcommonSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" .Values.tenant.id .Values.tenantcommonSecrets.secretName }}
  labels:
    {{- include "tenant-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.tenantcommonSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "tenant-app.name" . }}-vault
    kind: SecretStore
  target:
    name: {{ printf "%s-%s" .Values.tenant.id .Values.tenantcommonSecrets.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ include "tenant-app.vaultPath" (dict "path" .Values.tenantcommonSecrets.remotePath "root" .) | quote }}
---
{{- end }}
{{- if .Values.servicecommonSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" .Values.tenant.id .Values.servicecommonSecrets.secretName }}
  labels:
    {{- include "tenant-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.servicecommonSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "tenant-app.name" . }}-vault
    kind: SecretStore
  target:
    name: {{ printf "%s-%s" .Values.tenant.id .Values.servicecommonSecrets.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ include "tenant-app.vaultPath" (dict "path" (.Values.servicecommonSecrets.remotePath | default "secret/k8s/<tenant_id>/service-common") "root" .) | quote }}
---
{{- end }}
{{- range $svc := .Values.services }}
{{- $name := $svc.name }}
{{- if and (eq (include "tenant-app.serviceEnabled" (dict "svc" $svc "disabledServices" $.Values.disabledServices)) "true") (eq (include "tenant-app.serviceSecretEnabled" (dict "root" $ "svc" $svc)) "true") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tenant-app.serviceSecretName" (dict "root" $ "service" $name) }}
  labels:
    {{- include "tenant-app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.serviceSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "tenant-app.name" $ }}-vault
    kind: SecretStore
  target:
    name: {{ include "tenant-app.serviceSecretName" (dict "root" $ "service" $name) }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ include "tenant-app.vaultPath" (dict "path" ($.Values.serviceSecrets.remotePath | default "secret/k8s/<tenant_id>/<service-name>") "root" $ "service" $name) | quote }}
---
{{- end }}
{{- end }}
