{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tenant-app.name" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.tenant.domain }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.tenant.domain }}
      http:
        paths:
{{- range $svc := .Values.services }}
{{- $name := $svc.name }}
{{- if and (eq (include "tenant-app.serviceEnabled" (dict "svc" $svc "disabledServices" $.Values.disabledServices)) "true") $svc.ingressPath }}
          - path: {{ $svc.ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" (include "tenant-app.slug" $) $name }}
                port:
                  number: {{ (index $svc.ports 0).containerPort }}
{{- end }}
{{- end }}
{{- end }}
