{{- if .Values.storage.createStorageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClass | default (printf "%s-sc" .Values.tenant.id) }}
provisioner: driver.longhorn.io
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
allowVolumeExpansion: true
{{- end }}
